# Generated by Django 3.2.13 on 2022-05-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220513_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='price_kharid',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
    ]
